image: Visual Studio 2019 Preview

version: 0.4.0-beta1

environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    NoPackageAnalysis: true  # Suppresses warning about SemVer 2.0.0 version suffixes when packing

clone_depth: 10

install:
  # Initialize the appveyor
  - powershell .build\setup_appveyor.ps1

  # The following can be used to install a custom version of .NET Core
  - ps: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.ps1" -OutFile "install-dotnet.ps1"
  - ps: .\install-dotnet.ps1 -Version 3.0.100 -InstallDir "dotnetcli"

before_build:
  - appveyor-retry dotnet restore -v Minimal Ajustee.Client.sln

build_script:
  - dotnet build "test\Ajustee.Client.Test" -c Debug
  - dotnet build "src\Ajustee.Client" -c Release

after_build:
  - dotnet pack src\Ajustee.Client\Ajustee.Client.csproj -c Release

test:
  assemblies:
    - test\Ajustee.Client.Test\bin\Debug\net40\Ajustee.Client.Test.dll
    - test\Ajustee.Client.Test\bin\Debug\net45\Ajustee.Client.Test.dll
    - test\Ajustee.Client.Test\bin\Debug\net46\Ajustee.Client.Test.dll
    - test\Ajustee.Client.Test\bin\Debug\net461\Ajustee.Client.Test.dll
    - test\Ajustee.Client.Test\bin\Debug\netcoreapp2.1\Ajustee.Client.Test.dll
    - test\Ajustee.Client.Test\bin\Debug\netcoreapp2.2\Ajustee.Client.Test.dll
    - test\Ajustee.Client.Test\bin\Debug\netcoreapp3.0\Ajustee.Client.Test.dll

artifacts:
  - path: 'src\**\*.nupkg'
    name: Nuget

# deploy:
#   - provider: Environment
#     name: Ajustee Github
#     on:
#       deploy_github_release: true